// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7TPI0wGc0RCVpKQz9pX_V3kHxj9WvHw',
    appId: '1:357029692119:web:43c819f825aff8cb762692',
    messagingSenderId: '357029692119',
    projectId: 'code-map-565bc',
    authDomain: 'code-map-565bc.firebaseapp.com',
    databaseURL: 'https://code-map-565bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'code-map-565bc.appspot.com',
    measurementId: 'G-81ZX37BB8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJ3vhfrhv6JG8hbnhkWvMnzyxRkA31JU',
    appId: '1:357029692119:android:9eece66edc1b0ecb762692',
    messagingSenderId: '357029692119',
    projectId: 'code-map-565bc',
    databaseURL: 'https://code-map-565bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'code-map-565bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcSwYhUXZXGHzVtY9p7hBfWmBehw6Cqrc',
    appId: '1:357029692119:ios:19f3ebf99f489632762692',
    messagingSenderId: '357029692119',
    projectId: 'code-map-565bc',
    databaseURL: 'https://code-map-565bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'code-map-565bc.appspot.com',
    iosBundleId: 'com.example.codeMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcSwYhUXZXGHzVtY9p7hBfWmBehw6Cqrc',
    appId: '1:357029692119:ios:ee6343d6734f94ac762692',
    messagingSenderId: '357029692119',
    projectId: 'code-map-565bc',
    databaseURL: 'https://code-map-565bc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'code-map-565bc.appspot.com',
    iosBundleId: 'com.example.codeMap.RunnerTests',
  );
}
